//  File: fn_varToStr.sqf
//	Author: Bryan "Tonic" Boardwine

//	Description: Takes the long-name (variable) and returns a display name for our virtual item.
private["_var"];
_var = param [0,"",[""]];
if(_var == "") exitWith {""};

switch (_var) do
{
	//Virtual Inventory Items
	case "life_inv_lethalinjector": {"致命注射器"};
	case "life_inv_oilu": {(localize "STR_Item_OilU")};
	case "life_inv_oilp": {(localize "STR_Item_OilP")};
	case "life_inv_heroinu": {(localize "STR_Item_HeroinU")};
	case "life_inv_heroinp": {"黑海洛因"};
	case "life_inv_cannabis": {(localize "STR_Item_Cannabis")};
	case "life_inv_marijuana": {(localize "STR_Item_Marijuana")};
	case "life_inv_apple": {"苹果"};
	case "life_inv_salema": {(localize "STR_Item_SalemaMeat")};
	case "life_inv_ornate": {(localize "STR_Item_OrnateMeat")};
	case "life_inv_mackerel": {(localize "STR_Item_MackerelMeat")};
	case "life_inv_tuna": {(localize "STR_Item_TunaMeat")};
	case "life_inv_mullet": {(localize "STR_Item_MulletMeat")};
	case "life_inv_catshark": {(localize "STR_Item_CatSharkMeat")};
	case "life_inv_turtle": {(localize "STR_Item_TurtleMeat")};
	case "life_inv_fishingpoles": {(localize "STR_Item_FishingPole")};
	case "life_inv_water": {(localize "STR_Item_WaterBottle")};
	case "life_inv_coffee": {(localize "STR_Item_Coffee")};
	case "life_inv_turtlesoup": {(localize "STR_Item_TurtleSoup")};
	case "life_inv_donuts": {(localize "STR_Item_Donuts")};
	case "life_inv_fuelE": {(localize "STR_Item_FuelE")};
	case "life_inv_fuelF": {(localize "STR_Item_FuelF")};
	case "life_inv_pickaxe": {(localize "STR_Item_Pickaxe")};
	case "life_inv_copperore": {(localize "STR_Item_CopperOre")};
	case "life_inv_ironore": {(localize "STR_Item_IronOre")};
	case "life_inv_ironr": {(localize "STR_Item_IronIngot")};
	case "life_inv_copperr": {(localize "STR_Item_CopperIngot")};
	case "life_inv_sand": {(localize "STR_Item_Sand")};
	case "life_inv_salt": {(localize "STR_Item_Salt")};
	case "life_inv_saltr": {(localize "STR_Item_SaltR")};
	case "life_inv_glass": {(localize "STR_Item_Glass")};
	case "life_inv_diamond": {(localize "STR_Item_DiamondU")};
	case "life_inv_diamondr": {(localize "STR_Item_DiamondC")};
	case "life_inv_tbacon": {(localize "STR_Item_TBacon")};
	case "life_inv_redgull": {(localize "STR_Item_RedGull")};
	case "life_inv_lollypop": {"药用棒棒糖"};
	case "life_inv_lockpick": {(localize "STR_Item_Lockpick")};
	case "life_inv_peach": {(localize "STR_Item_Peach")};
	case "life_inv_coke": {"未经加工的可卡因"};
	case "life_inv_cokep": {"加工后的可卡因"};
	case "life_inv_spikeStrip": {(localize "STR_Item_SpikeStrip")};
	case "life_inv_rock": {(localize "STR_Item_Rock")};
	case "life_inv_cement": {(localize "STR_Item_CementBag")};
	case "life_inv_goldbar": {(localize "STR_Item_GoldBar")};
	case "life_inv_moneybag": {"钱袋子"};
	case "life_inv_blastingcharge": {(localize "STR_Item_BCharge")};
	case "life_inv_boltcutter": {(localize "STR_Item_BCutter")};
	case "life_inv_fireaxe": {(localize "STR_Item_FAxe")};
	case "life_inv_defusekit": {(localize "STR_Item_DefuseKit")};
	case "life_inv_storagesmall": {(localize "STR_Item_StorageBS")};
	case "life_inv_storagebig": {(localize "STR_Item_StorageBL")};
	case "life_inv_potato": {(localize "STR_Item_Potato")};
	case "life_inv_cream": {(localize "STR_Item_Cream")};
	case "life_inv_frog": {"青蛙"};
	case "life_inv_frogp": {"迷幻青蛙"};
	case "life_inv_crystalmeth": {"蓝水晶冰毒"};
	case "life_inv_methu": {"未加工的冰毒"};
	case "life_inv_phosphorous": {"红磷"};
	case "life_inv_ephedra": {"麻黄属植物"};
	case "life_inv_lithium": {"锂岩"};
	case "life_inv_moonshine": {"私酒"};
	case "life_inv_rum": {"朗姆酒"};
	case "life_inv_mashu": {"酸醪"};
	case "life_inv_corn": {"玉米"};
	case "life_inv_sugar": {"食用糖"};
	case "life_inv_yeast": {"酵母"};
	case "life_inv_platinum": {"白金块"};
	case "life_inv_platinumr": {"铂金锭"};
	case "life_inv_silver": {"银矿石"};
	case "life_inv_silverr": {"银锭"};
	case "life_inv_beer": {"啤酒"};
	case "life_inv_ziptie": {"绑带"};
	case "life_inv_cupcake": {"纸杯蛋糕"};
	case "life_inv_pepsi": {"百事可乐"};
	case "life_inv_burger": {"有机汉堡"};
	case "life_inv_mushroom": {"蘑菇"};
	case "life_inv_mmushroom": {"加工蘑菇"};
	case "life_inv_mmushroomp": {"蘑菇披萨"};
	case "life_inv_gpstracker": {"GPS跟踪器"};
	case "life_inv_egpstracker": {"增强型GPS跟踪器"};
	case "life_inv_gpsjammer": {"GPS干扰器"};
	case "life_inv_ccocaine": {"可卡因"};
	case "life_inv_kidney": {"黑市肾脏"};
	case "life_inv_scalpel": {"手术刀"};
	case "life_inv_barrier": {"屏障"};
	case "life_inv_speedbomb": {"高速炸弹"};
	case "life_inv_foodDiv": 	{"-------- 食物类 --------"};
	case "life_inv_legalDiv": 	{"-------- 合法类 --------"};
	case "life_inv_illegalDiv": {"-------- 非法类 --------"};
	case "life_inv_fireworks": {"烟花"};
	case "life_inv_heliTowHook": {"拖钩和吊索"};
	case "life_inv_chickenRaw": {"生鸡肉"};
	case "life_inv_roosterRaw": {"生公鸡"};
	case "life_inv_goatRaw": {"生山羊"};
	case "life_inv_sheepRaw": {"生羊"};
	case "life_inv_rabbitRaw": {"生兔"};
	case "life_inv_snakeRaw": {"生蛇肉"};
	case "life_inv_chicken": {"加工鸡肉"};
	case "life_inv_rooster": {"加工的公鸡"};
	case "life_inv_goat": {"加工山羊"};
	case "life_inv_sheep": {"加工绵羊"};
	case "life_inv_rabbit": {"加工兔子"};
	case "life_inv_snake": {"加工蛇肉"};
	case "life_inv_bloodbag": {"血袋"};
	case "life_inv_epiPen": {"肾上腺素"};
	case "life_inv_dopeShot": {"多巴胺注射"};
	case "life_inv_woodLog": {"原木"};
	case "life_inv_lumber": {"木材"};
	case "life_inv_bananau": {"香蕉"};
	case "life_inv_bananap": {"香蕉片"};
	case "life_inv_topaz": {"未切割黄玉"};
	case "life_inv_topazr": {"黄玉"};
	case "life_inv_cocoau": {"生可可"};
	case "life_inv_cocoap": {"巧克力"};
	case "life_inv_bananaSplit": {"香蕉叶"};
	case "life_inv_sugarp": {"方糖"};
	case "life_inv_hackingterminal": {"黑客终端"};
	case "life_inv_takeoverterminal": {"接管终端"};
	case "life_inv_blindfold": {"头套"};
	case "life_inv_panicButton": {"紧急按钮"};
	case "life_inv_wplPanicButton": {"紧急按钮"};
	case "life_inv_roadKit": {"公路工具箱"};
	case "life_inv_oilbarrel": {"油桶"};
	case "life_inv_vehAmmo": {"车辆弹药"};
	case "life_inv_baitcar": {"鱼饵用具"};
	case "life_inv_wpearl": {"白色的珍珠"};
	case "life_inv_bpearl": {"蓝珍珠"};
	case "life_inv_amethyst": {"紫晶"};
	case "life_inv_coin": {"杜布隆"};
	case "life_inv_emerald": {"翡翠"};
	case "life_inv_scrap": {"废金属"};
	case "life_inv_hash": {"搞砸"};
	case "life_inv_acid": {"酸"};
	case "life_inv_crack": {"可卡因"};
	case "life_inv_mushroomu": {"神器蘑菇"};
	case "life_inv_pheroin": {"纯海洛因"};
	case "life_inv_painkillers": {"止痛药"};
	case "life_inv_excavationtools": {"挖掘工具"};
	case "life_inv_rubber": {"橡胶"};
	case "life_inv_alumore": {"铝矿石"};
	case "life_inv_coal": {"煤块"};
	case "life_inv_fibers": {"纤维"};
	case "life_inv_stire": {"小轮胎"};
	case "life_inv_ltire": {"大轮胎"};
	case "life_inv_window": {"窗户"};
	case "life_inv_rglass": {"钢化玻璃"};
	case "life_inv_vdoor": {"车门"};
	case "life_inv_electronics": {"电气元件"};
	case "life_inv_smetal": {"金属板"};
	case "life_inv_splating": {"钢板"};
	case "life_inv_alumalloy": {"铝合金"};
	case "life_inv_bcremote": {"诱饵汽车遥控器"};
	case "life_inv_paintingSm": {"小型绘画"};
	case "life_inv_paintingLg": {"大型绘画"};
	case "life_inv_gokart": {"小型卡丁车"};

	//License Block
	case "license_civ_driver": {(localize "STR_License_Driver")};
	case "license_civ_air": {(localize "STR_License_Pilot")};
	case "license_civ_heroin": {(localize "STR_License_Heroin")};
	case "license_civ_oil": {(localize "STR_License_Oil")};
	case "license_civ_dive": {(localize "STR_License_Diving")};
	case "license_civ_boat": {(localize "STR_License_Boat")};
	case "license_civ_gun": {(localize "STR_License_Firearm")};
	case "license_civ_wpl": {(localize "STR_License_WPL")};
	case "license_cop_air": {(localize "STR_License_Pilot")};
	case "license_cop_swat": {(localize "STR_License_Swat")};
	case "license_cop_cg": {(localize "STR_License_CG")};
	case "license_civ_rebel": {(localize "STR_License_Rebel")};
	case "license_civ_truck": {(localize "STR_License_Truck")};
	case "license_civ_diamond": {(localize "STR_License_Diamond")};
	case "license_civ_copper": {(localize "STR_License_Copper")};
	case "license_civ_iron": {(localize "STR_License_Iron")};
	case "license_civ_sand": {(localize "STR_License_Sand")};
	case "license_civ_salt": {(localize "STR_License_Salt")};
	case "license_civ_coke": {(localize "STR_License_Cocaine")};
	case "license_civ_marijuana": {(localize "STR_License_Marijuana")};
	case "license_civ_cement": {(localize "STR_License_Cement")};
	case "license_med_air": {(localize "STR_License_Pilot")};
	case "license_med_cg": {(localize "STR_License_MCG")};
	case "license_civ_home": {(localize "STR_License_Home")};
	case "license_civ_frog": {"偷猎青蛙许可证"};
	case "license_civ_crystalmeth": {"冰晶加工"};
	case "license_civ_methu": {"冰毒加工"};
	case "license_civ_moonshine": {"私酒加工"};
	case "license_civ_mashu": {"酸醪加工"};
	case "license_civ_platinum": {"铂金加工"};
	case "license_civ_silver": {"银加工"};
	case "license_civ_vigilante": {"维吉兰特执照"};
	case "license_civ_mushroom": {"蘑菇加工"};

	case "license_civ_lumber": {"锯木厂会员"};
	case "license_civ_bananap": {"香蕉工厂会员"};
	case "license_civ_topaz": {"黄玉加工"};
	case "license_civ_cocoap": {"可可加工"};
	case "license_civ_bananaSplit": {"香蕉人的友谊"};
	case "license_civ_sugarp": {"制糖加工"};

	//For APD Training Dummy IDK WHERE ELSE TO PUT THIS OKAY
	case "license_fake": {"<t color='#FF0000'><t size='2'>[OS] 麦迪利</t></t><br/><t color='#FFD700'><t size='1.5'>证件:</t></t><br/>驾驶执照<br/>Pilot License<br/>海洛因训练<br/>Firearm License<br/>Sand Processing<br/>Marijuana Training<br/>"};
	case "fake_search": {"<t color='#FF0000'><t size='2'>[OS] 麦迪利</t></t><br/><t color='#FFD700'><t size='1.5'>Weapons</t></t><br/><t color='#FFFFFF'><t color='#FFFFFF'>MAR-10 .338 (Camo)</t><br/>.338 LM 10Rnd Mag</t><br/><br/><t color='#FFD700'><t size='1.5'>Backpack Content</t></t><br/>No items in backpack.<br/><br/><t color='#FFD700'><t size='1.5'>Vest Content</t></t><br/><t color='#FFFFFF'>.338 LM 10Rnd Mag x8</t><br/><br/><t color='#FFD700'><t size='1.5'>Uniform Content</t></t><br/><t color='#FFFFFF'>.338 LM 10Rnd Mag x1</t><br/><br/><t color='#FFD700'><t size='1.5'>Illegal Items</t></t><br/>Lockpick x15<br/>Blasting Charge x1<br/>Hacking Terminal x3<br/>Scalpel x3<br/>Vehicle Ammo x1<br/><br/><br/><br/><br/><t color='#FF0000'></t>"};
};
